
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavWrapper from "./NavWrapper";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<NavWrapper>{children}</NavWrapper>
			</body>
		</html>
	);
}

